### ISSUE TITLE
demo跑不起来啊

### ISSUE THREAD

**Issue by jacintoface** [Siy-Wu/ExcludeAar#1]

**Comment by ssiyy** [comment]
不会吧，报什么错？

**Comment by jacintoface** [comment]
build.gradle #33 resValue "string", "baiduKey", gradle.baidukey
报错 Build Config field connot have a null parameter

**Comment by ssiyy** [comment]
额，你自己申请一个百度地图的key，配置进去就可以了

**Comment by ssiyy** [comment]
在项目的app module 的build.gradle的脚本中。

 buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            resValue "string", "baiduKey", gradle.baidukey
            signingConfig signingConfigs.keyTest
        }
        debug{
            resValue "string", "baiduKey", gradle.baidukey
            signingConfig signingConfigs.keyTest
        }
    }

 gradle.baidukey就是用来读取local.properties的baidukey的，所以你只需要在local.properties文件配置一个百度的key它名字是baidukey就可以了

**Comment by jacintoface** [comment]
<img width="1713" alt="2018-10-19 5 06 49" src="https://user-images.githubusercontent.com/25702304/47208840-7d5a0300-d3c1-11e8-8eee-c2f46091e9f1.png">
我在网上搜了一个,但是好像还是报错了呢 Thanks

**Comment by Apollolight** [comment]
我也是这个错，解决了么

**Comment by Apollolight** [comment]
重新build一下就可以跑了，错误提示是找不到包，这个路径是build下的路径，build下的路径都是可以rebuild一下产生的。
至于项目为什么跑不起来，感觉是因为作者删除了local.properties下面的几个变量，自己把用到这几个变量的地方直接改掉就好了
