### ISSUE TITLE
执行任务后，aar里面要过滤的包名是没看到了，但是点击as “运行”按钮，出现：Duplicate class cn.sirius.nga.BuildConfig found in modules jetified-exclude_GDTSDK_unionNormal-runtime.jar (exclude_GDTSDK_unionNormal.aar) and jetified-XXX_sdk_v3.1.0-runtime.jar (:XXX_sdk_v3.1.0:)

### ISSUE THREAD

**Issue by jackom** [Siy-Wu/ExcludeAar#10]
作者你好，我集成了你的开源库，执行任务后，aar里面要过滤的包名是没看到了，但是点击as “运行”按钮，出现：Duplicate class cn.sirius.nga.BuildConfig found in modules jetified-exclude_GDTSDK_unionNormal-runtime.jar (**exclude_GDTSDK_unionNormal.aar**) and jetified-XXX_sdk_v3.1.0-runtime.jar (:XXX_sdk_v3.1.0:)

![image](https://user-images.githubusercontent.com/5052960/93580164-fc06b300-f9d1-11ea-80ae-50079197fad9.png)

**Comment by ssiyy** [comment]
cn.sirius.nga.BuildConfig 这各类冲突了，你把这个类也过滤一下试试

**Comment by jackom** [comment]
> cn.sirius.nga.BuildConfig 这各类冲突了，你把这个类也过滤一下试试

![image](https://user-images.githubusercontent.com/5052960/93581242-73891200-f9d3-11ea-84f8-dabd9a634e42.png)
![image](https://user-images.githubusercontent.com/5052960/93581979-6caecf00-f9d4-11ea-8e7d-191ff7fa4968.png)

过滤了也不行。

![image](https://user-images.githubusercontent.com/5052960/93581712-1c377180-f9d4-11ea-8171-ee1010a283ed.png)

 我在想，是不是因为 app -> libs下有我的aar文件，而 执行移除aar中某个包名后，生成的build/excludePlguin/excludeaar/exclude_GDTSDK_unionNormal.aar文件，里面跟我现在的aar文件重复了，所以导致的问题？

**Comment by ssiyy** [comment]
是这样的，你可以仿照我的demo一样在libs里面新建一个exclude文件夹，这样被过滤的aar包就不会被引用到，你再autoDependencies  等于true就会自动引用到过滤后的aar包，就不会冲突了

**Comment by jackom** [comment]
> 是这样的，你可以仿照我的demo一样在libs里面新建一个exclude文件夹，这样被过滤的aar包就不会被引用到，你再autoDependencies 等于true就会自动引用到过滤后的aar包，就不会冲突了

好的，我再试试，谢谢了~

**Comment by jackom** [comment]
楼主你好，我这边测试了，还是会跟之前一样的报错。。不清楚是哪里出了问题了。
![image](https://user-images.githubusercontent.com/5052960/93584755-54d94a00-f9d8-11ea-902b-1d5d1608ccfe.png)
![image](https://user-images.githubusercontent.com/5052960/93584879-8520e880-f9d8-11ea-95dc-b5edc60a65af.png)
![image](https://user-images.githubusercontent.com/5052960/93585031-c31e0c80-f9d8-11ea-939c-fd39417626cb.png)

**Comment by ssiyy** [comment]
你引用了2次

**Comment by ssiyy** [comment]
<img width="748" alt="微信图片_20200918180249" src="https://user-images.githubusercontent.com/13219494/93585342-3758b000-f9d9-11ea-9f3d-960568d7efac.png">
你配置了autoDependencies  为true 我会自动帮你引用过滤之后的aar包，你不需要要自己再implementtation files('libs/exclude/xxxxx.aar')

**Comment by jackom** [comment]
> 你引用了2次

哪个地方阿？ 执行移除aar中某个包名的任务后，生成的build/excludePlguin/excludeaar/exclude_GDTSDK_unionNormal.aar文件，里面跟我现在的libs/exclude/XXX_aar文件重复了
![image](https://user-images.githubusercontent.com/5052960/93585375-47708f80-f9d9-11ea-837f-90c10b96010c.png)

**Comment by jackom** [comment]
好的，我再试下。

**Comment by jackom** [comment]
现在是可以正常运行了。谢谢楼主！
