### ISSUE TITLE
先自动化检测主module跟放在libs/exclude文件夹内的aar文件之间存在的冲突包名，然后再过滤那些冲突的包名，这种该怎么实现呢？

### ISSUE THREAD

**Issue by jackom** [Siy-Wu/ExcludeAar#11]
楼主你好，有个问题想请教下：目前这个开源库是要先在

`
excludePluginExt {
        autoDependencies = true //是否自动依赖即是否依赖过滤之后的架包
        aars {
            BaiduLBS_Android_debug { //过滤架包的名称
                path "/libs/exclude/BaiduLBS_Android_debug.aar" //架包的路径
                excludePackages 'com.baidu.location' //过滤的包名
            }
        }
        jars{
            BaiduLBS_Android_7_5_2{//过滤架包的名称
                path "/libs/exclude/BaiduLBS_Android_7.5.2.jar" //架包的路径
                excludePackages 'com.baidu.android','com.baidu.lbsapi' //过滤的包名
            }

            map_baidu{//过滤架包的名称
                path "/libs/exclude/map-baidu.jar"//架包的路径
                excludePackages "io.dcloud.js.map.adapter"//过滤的包名
                excludeClasses "io.dcloud.js.map.IFMapDispose","io.dcloud.js.map.JsMapCircle","io.dcloud.js.map.MapJsUtil"//过滤的类名
            }
        }
    }
`

这里声明要过滤的包名啥的，然后再执行指定的Task。如果要实现：先自动化检测主module跟放在libs/exclude文件夹内的aar文件之间存在的冲突包名，然后再过滤那些冲突的包名，这种该怎么实现呢？

**Comment by ssiyy** [comment]
插件中有个过滤包的任务createExclueAarTask 啥的你可以再gradle task列表中找到， 你用指定的任务dependsOn 它就行了

**Comment by jackom** [comment]
我在gradle那找了好几遍，没看到有类似 createExclueAarTask 啥的 任务阿、

**Comment by ssiyy** [comment]
有的，只是我在重构用kotlin写的插件中隐藏掉了，为了方便接入使用变成了自动调用了，但是你还是可以在groovy代码中找到它。

**Comment by ssiyy** [comment]
<img width="357" alt="微信截图_20200921110954" src="https://user-images.githubusercontent.com/13219494/93730411-0d7ed380-fbfb-11ea-9b11-a10f3af3b5c5.png">
在这里：https://github.com/Siy-Wu/ExcludeAar/blob/master/libraries/library-exclude-aar/excludeAar.gradle

**Comment by jackom** [comment]
好的，我后面找到这里去了。。
![image](https://user-images.githubusercontent.com/5052960/93730488-71090100-fbfb-11ea-96d7-4e8b6f137c05.png)

**Comment by jackom** [comment]
这里还是有些疑问：“用指定的任务dependsOn 它就行了”。这个是说需要在主module的build.gradle那里创建个Task，然后先 dependsOn 它，然后再替换掉
`excludePluginExt {
    autoDependencies = true //是否自动依赖即是否依赖过滤之后的架包
    aars {
        GDTSDK_unionNormal { //过滤架包的名称
            path "/libs/exclude/XXX_sdk_v3.1.8.aar" //架包的路径
            excludePackages 'com.qq.e' //过滤的包名
        }
    }
}`
这里面的  'com.qq.e' //过滤的包名 ？

**Comment by ssiyy** [comment]
你可以创建一个Task 检查出哪些是需要过滤的文件，然后修改过滤配置再执行过滤任务

**Comment by jackom** [comment]
是的，我现在就卡在这里了。。 /手动狗头               我目前的想法是：创建一个Task 检查出哪些是需要过滤的文件，然后用 那些包名去替换掉 
`
excludePluginExt {
    autoDependencies = true //是否自动依赖即是否依赖过滤之后的架包
    aars {
        GDTSDK_unionNormal { //过滤架包的名称
            path "/libs/exclude/XXX_sdk_v3.1.8.aar" //架包的路径
            excludePackages **'com.qq.e'** //过滤的包名
        }
    }
}
`
这里面的 'com.qq.e'，从而达到想要的结果。只是目前 对 groovy不熟，不知道怎么下手。。

**Comment by jackom** [comment]
我再研究下 怎么在Task中实现过滤文件的逻辑。。

**Comment by ssiyy** [comment]
你可以看下https://github.com/Siy-Wu/ExcludeAar/blob/master/libraries/library-exclude-aar/excludeAar.gradle 地方应该可以给你一下啊思路，实在不了解可以用Java写的，groovy文件中可以写Java代码

**Comment by jackom** [comment]
嗯，我先试试，谢谢了哈。

**Comment by jackom** [comment]
还有就是：资源冲突的话，有好的解决方案吗？主module跟引入的aar或者aar跟aar之间的资源冲突

**Comment by ssiyy** [comment]
可以扫面aar文件的R文件找出冲突的资源，但是我也没有好办法做修改，因为可能aar程序中可能会有引用到

**Comment by jackom** [comment]
大佬，可以帮忙实现下或者提供关键代码吗？检查出哪些是需要过滤的文件这块我搞了一天了还是没搞出来。。。我参考了[这篇博客](https://blog.csdn.net/mgarfield/article/details/45057007?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-3.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-3.channel_param)的去搞的。
![image](https://user-images.githubusercontent.com/5052960/93870319-a3038b80-fcff-11ea-915b-dc85ea15dbcf.png)
