### ISSUE TITLE
需要导出为aar的library中需要导入另外的aar，应该如何配置？

### ISSUE THREAD

**Issue by ykrank** [Siy-Wu/ExcludeAar#12]
现在有个比较特殊的需求，A.aar是放在library B中的，然后需要library B打包成B.aar给主项目用。要求A.aar的代码被flat到B中，而不是主项目直接引用A.aar。A.aar中有个so需要被去除，因为和主项目冲突了。
我使用demo的方法，去除倒的确是去除了，但是使用assembleRelease生成的B.aar里面代码结构很奇怪，主class.jar里面压缩了另外一个class.jar，里面就是A的代码。
![image](https://user-images.githubusercontent.com/6565673/94634535-e44cfa00-0302-11eb-8b0b-91c430a012cf.png)
导入时便会class not found了。
这个怎么解决呢？

**Comment by ykrank** [comment]
我使用了autoDependencies = true

**Comment by ssiyy** [comment]
使用了autoDependencies = true 就不能依赖被过滤的aar额，你检查一下是否依赖了被过滤的aar

**Comment by ykrank** [comment]
最终还是手动去掉了依赖，B里面使用了compileOnly，直接在主项目依赖了A.aar
