### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'exclude_library-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

### ISSUE THREAD

**Issue by ifmvo** [Siy-Wu/ExcludeAar#2]
Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'exclude_library-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

**Comment by ifmvo** [comment]
亲、和 issues/1 是一样的问题

**Comment by ssiyy** [comment]
你好，我自己运行确认一下，改了之后再通知你，不好意思哈

**Comment by ifmvo** [comment]
我遇到的问题是：我自己的项目中使用到了百度广告的jar包，项目中还添加了一个第三方的aar，这个aar里面也有百度广告的jar包，两个com.baidu.mobs发生冲突，并且这两个jar包不是一个版本的，所以请问@Siy-Wu 有没有什么好的方法解决这种问题？

**Comment by ifmvo** [comment]
这个问题已经解决
Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'exclude_library-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
出现这个问题的时候只需要 cleanProject 在运行就可以了

**Comment by ssiyy** [comment]
嗯，不好意思，最近工作忙没有时间看，希望ExcludeAar能解决你遇到的问题
