### ISSUE TITLE
aar的使用方式是否需要修改

### ISSUE THREAD

**Issue by huaxiaos** [Siy-Wu/ExcludeAar#3]
作者你好：

如果按照github项目中的方式来处理，那集成aar的方式就需要修改了吧，需要给每一个aar指定一个特定的configuration是么？感觉这样有点麻烦

能否直接根据aar的name来获取到aar文件路径呢？

**Comment by Siy-Wu** [comment]
可以的，你可以根据sourceSet可以拿到aar的路径

**Comment by ssiyy** [comment]
可以的
