### ISSUE TITLE
运行demo必须是studio版本3.5以上吗

### ISSUE THREAD

**Issue by shenyunmeng0519** [Siy-Wu/ExcludeAar#5]

**Comment by ssiyy** [comment]
不用，只是我自己用的是3.5而已

**Comment by shenyunmeng0519** [comment]
具体用法怎么用的呢，我想删除两个aar包中的某个冲突的包下面的文件，应该怎么用呢

**Comment by ssiyy** [comment]
你按照我demo中的方法配置就行了。

1，你把:library-exclude-aar工程拷贝到你的项目中
2，把:library-exclude-aar中的BaiduLBS_Android_release.aar替换成你自己的aar包
3，把:library-exclude-aar中build.gradle文件名也改成你自己aar包的名称
4，然后在:library-exclude-aar中的excludeAar.gradle文件里面配置过滤规则
5，在你自己的主工程  implementation project(configuration: 'exclude', path: ':library-exclude-aar')
6，最后运行excludeAar任务执行过滤

ok！完成

**Comment by ssiyy** [comment]
我后面把它写成一个gradle插件吧。^_^

**Comment by shenyunmeng0519** [comment]
library-exclude-aar这个放到我项目中那个目录下面呢

**Comment by ssiyy** [comment]
如果你严格按照我上面说的步骤，你就应该放在根目录下面(因为':library-exclude-aar'这个path对应的就是这儿)，但是要记住**library-exclude-aar这个工程也要在setting.gradle注册一下**

**Comment by shenyunmeng0519** [comment]
我要过滤的是xwalk_core_library_release.aar，这个aar中的org.chromium这个包，我应该在library-exclude-aar中的excludeAar.gradle中改哪些东西？
![image](https://user-images.githubusercontent.com/14258234/68371807-7774c280-017a-11ea-8fb2-a988b5d8e53e.png)

**Comment by ssiyy** [comment]
//需要过滤的包名
def excludePackages = ['com.baidu']
//需要过滤的类(需要全类名)
def excludeClasses = []

在过滤包的地方填入org.chromium就可以了

**Comment by shenyunmeng0519** [comment]
![image](https://user-images.githubusercontent.com/14258234/68373563-1f3fbf80-017e-11ea-9814-3a26689b3054.png)
我是哪里写的不对吗

**Comment by ssiyy** [comment]
你要在setting.gradle注册一下

**Comment by ssiyy** [comment]
配置完了之后还要运行一下excludeAar任务额

**Comment by shenyunmeng0519** [comment]
![image](https://user-images.githubusercontent.com/14258234/68373882-b4db4f00-017e-11ea-8c35-a20ecad72870.png)
麻烦问下如何运行那个任务

**Comment by ssiyy** [comment]
你多放了一级，改成:library-exclude-aar，注：我有2级是因为我放在libraries下面

![TIM图片20191107165941](https://user-images.githubusercontent.com/13219494/68374411-d557d900-017f-11ea-8e43-668ec6f251e2.png)

**Comment by shenyunmeng0519** [comment]
麻烦问下有啥联系方式吗？这样太费劲了

**Comment by ssiyy** [comment]
运行一下就可以了，生成过滤包就行了，以后就不用管了。

**Comment by shenyunmeng0519** [comment]
![image](https://user-images.githubusercontent.com/14258234/68374994-efde8200-0180-11ea-9aa3-9bc0ae2a6053.png)
没有你那个选择，然后还报错
![image](https://user-images.githubusercontent.com/14258234/68375018-fb31ad80-0180-11ea-88e9-0294e73b999e.png)

**Comment by Siy-Wu** [comment]
![TIM截图20191107171022](https://user-images.githubusercontent.com/13219494/68375134-36cc7780-0181-11ea-9812-d5f01f4645e7.png)

**Comment by Siy-Wu** [comment]
你配错了

**Comment by shenyunmeng0519** [comment]
setting文件已经改过了，不知道哪里还要改
![image](https://user-images.githubusercontent.com/14258234/68375498-eace0280-0181-11ea-9cb7-660710ab0a20.png)

**Comment by ssiyy** [comment]
![TIM截图20191107171341](https://user-images.githubusercontent.com/13219494/68375502-ebff2f80-0181-11ea-9e77-320c24fc049d.png)
![TIM截图20191107171443](https://user-images.githubusercontent.com/13219494/68375505-ed305c80-0181-11ea-8db1-779d182a414f.png)

**Comment by shenyunmeng0519** [comment]
路径已经改过了，依然报错
![image](https://user-images.githubusercontent.com/14258234/68375823-82cbec00-0182-11ea-9023-b9087d7d0ae2.png)

**Comment by ssiyy** [comment]
![TIM截图20191107172107](https://user-images.githubusercontent.com/13219494/68375953-b6a71180-0182-11ea-8938-8c02e948f42f.png)
你自己用as新建一个包含aar的module吧，不要复制我的module了，这样路径就不会错了

然后你在把excludeAar.gradle这个脚本拷贝过滤，其实主要功能就是这个脚本完成的

**Comment by ssiyy** [comment]
然后你在你新建的module中找到build.gradle文件，
添加 apply from: "${project.projectDir.absoluteFile}\\excludeAar.gradle" 这句。（就是把excludeAar.gradle引入的意思）

注意excludeAar.gradle的路径不要放错了和build.gradle文件平级的。

![TIM截图20191107172544](https://user-images.githubusercontent.com/13219494/68376299-58c6f980-0183-11ea-864b-120021ce2fce.png)

**Comment by shenyunmeng0519** [comment]
![image](https://user-images.githubusercontent.com/14258234/68376915-6fba1b80-0184-11ea-9164-11fdc25bdd2e.png)
![image](https://user-images.githubusercontent.com/14258234/68376924-734da280-0184-11ea-861e-57a24da1fcfc.png)
![image](https://user-images.githubusercontent.com/14258234/68376935-79dc1a00-0184-11ea-8001-9e0a1ce6ddc8.png)
![image](https://user-images.githubusercontent.com/14258234/68376967-89f3f980-0184-11ea-95d7-c2ca5dd1e7df.png)
![image](https://user-images.githubusercontent.com/14258234/68376992-9415f800-0184-11ea-934f-02752d14d350.png)我已经不知道还要设置哪里了，依然报错
![image](https://user-images.githubusercontent.com/14258234/68377021-9ed08d00-0184-11ea-8051-bd40e5db6945.png)

**Comment by ssiyy** [comment]
你搞错了呀，
![TIM截图20191107173717](https://user-images.githubusercontent.com/13219494/68377229-f5d66200-0184-11ea-982f-7389478c80f9.png)

谁要你到这个包的，ε=(´ο｀*)))

我脚本里面没有导入任何包

**Comment by ssiyy** [comment]
![TIM截图20191107173814](https://user-images.githubusercontent.com/13219494/68377318-17374e00-0185-11ea-91e9-affb22e21fae.png)

**Comment by ssiyy** [comment]
删了应该就可以了

**Comment by shenyunmeng0519** [comment]
我擦，自己导的吗？我直接复制过来的

**Comment by ssiyy** [comment]
行吧，希望可以解决你的问题，如果有帮到你就star一下，后面我会改成插件的形式，然后支持多架包过滤

**Comment by shenyunmeng0519** [comment]
好了是好了，但是我发现我这个是aar中的Jar里面的一个包，那样运行后并不能删除，唉

**Comment by ssiyy** [comment]
![TIM截图20191107175821](https://user-images.githubusercontent.com/13219494/68378931-ee648800-0187-11ea-84e7-b0d357fe2878.png)
那是因为你的aar包不是release打出来的。我写的脚本只能过滤classes.jar里面的包和class。并不能过滤其它的，因为我不可能知道你的aar中还可能有拿些其它名称的jar(如：你的xwalk_core_library.jar)

**Comment by shenyunmeng0519** [comment]
嗯嗯，但是还是感谢

**Comment by ssiyy** [comment]
如果是realease打出来的，aar中的三方jar会被合并到classesjar中,像这样：
![TIM截图20191107180416](https://user-images.githubusercontent.com/13219494/68379403-bc075a80-0188-11ea-8240-5f91b354c55c.png)
不过你的需求我知道，我会后面支持对aar中自定jar包名称进行过滤，而不默认只对classes.jar过滤。

**Comment by ssiyy** [comment]
如果你仔细看那个脚本，也可以自己改。
![TIM截图20191107180811](https://user-images.githubusercontent.com/13219494/68379665-4780eb80-0189-11ea-9b8e-664e6b6c1d47.png)

**Comment by shenyunmeng0519** [comment]
感谢，已经完美解决了我的问题，改了你的脚本
